language: node_js
node_js:
  - 12.8.0

cache: yarn
install:
  - yarn config set registry https://registry.npmjs.org
  - yarn install
  - yarn build-insee
  - yarn build-storybook
script:
  - yarn test:coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/gitbook.sh
