language: node_js
node_js:
  - 12.8.0
addons:
  sonarcloud:
    organization: "inseefr"
cache: yarn
install:
  - yarn config set registry https://registry.npmjs.org
  - yarn
before_script:
  - yarn build-insee
  - yarn build-storybook
  - yarn test:coverage
script:
  - sonar-scanner

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/gitbook.sh
