name: Quality
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 21, 22 ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Generic CI For Building the Application
        uses: ./.github/actions/generic-ci-app
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}

