name: Quality
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - documentation/**
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  test-build:
    name: Test & Build & Deploy Sonar report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Generic CI For Building the Application
        uses: ./.github/actions/generic-ci-app
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout BackOffice
        uses: actions/checkout@v4
        with:
          repository: inseefr/drama-queen
          path: drama-queen
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci --force
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: './drama-queen/docker-compose.yml'
          test-command: 'npx playwright test'
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
