name: Quality
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - documentation/**
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout BackOffice
        uses: actions/checkout@v4
        with:
          repository: inseefr/bauhaus-back-office
          ref: 787-publication-des-triplets-uriserie-dcthaspart-urioperation
          path: ./bauhaus-back-office
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci --force
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: LS
        run: ls -al bauhaus-back-office
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: './bauhaus-back-office/compose.yaml'
          test-command: 'npx playwright test'
  test-build:
    name: Test & Build & Deploy Sonar report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Generic CI For Building the Application
        uses: ./.github/actions/generic-ci-app
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
