name: GHCR
on:
  issue_comment:
    types:
      - created
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy to Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT" =~ ^deploy ]]; then
          echo "comment starts with 'deploy'"
          exit 0
          else
          echo "comment did not start with 'deploy'"
          exit 1
          fi
      - uses: actions/checkout@v4
      - name: Log in to ghcr.io
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build, tag and deploy image
        run: |
          TAG=$(echo "$COMMENT" | awk '{print $2}')
          docker build -t ghcr.io/emmanueldemey/bauhaus:$TAG -f ./Dockerfile .
          docker push ghcr.io/emmanueldemey/bauhaus:$TAG
