name: Bauhaus CI
on: [push]
jobs:
  test-build:
    name: Build the documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.8.0
      - run: yarn
      # Build modules
      - run: ./scripts/gitbook.sh
  deploy:
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
