name: Documentation
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.8.0
      - run: ./scripts/gitbook.sh
  deploy:
    #if: github.ref == 'refs/heads/master'
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ls -al
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
