name: Release
on:
  release:
    types: [prereleased]
    branches:
      - main
    paths-ignore:
      - documentation/**
jobs:
  build:
    name: Test & Build & Upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Generic CI For Building the Application
        uses: ./.github/actions/generic-ci-app
      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        id: download
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: ${{ github.repository_owner }}/bauhaus:${{ env.VERSION }}
