name: Build and Deploy Documentation On Main
on:
  push:
    branches:
      - "main"
    paths:
      - .github/
      - documentation/**
jobs:
  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Generic CI For Documentation
        uses: ./.github/actions/generic-ci-documentation
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
