name: Build Documentation on PR
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  deploy:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Generic CI For Documentation
        uses: ./.github/actions/generic-ci-documentation
