name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout BackOffice
        uses: actions/checkout@v4
        with:
          repository: inseefr/drama-queen
          path: drama-queen
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci --force
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: './drama-queen/docker-compose.yml'
          test-command: 'npx playwright test'
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
